[project]
name = "housing-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "certifi>=2024.12.14",
    "charset-normalizer>=3.4.1",
    "idna>=3.10",
    "iniconfig>=2.0.0",
    "jeepney>=0.8.0",
    "loguru>=0.6.0",
    "lxml>=5.3.0",
    "notify-py>=0.3.43",
    "packaging>=24.2",
    "pluggy>=1.5.0",
    "pync>=2.0.3",
    "requests>=2.32.3",
    "urllib3>=2.3.0",
]

[project.scripts]
monitor = "monitor"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.13",
    "ty>=0.0.36",
]
